services:
  telegram-bot:
    build: ./docker/telegram-bot
    environment:
      TELEGRAM_BOT_TOKEN: "PUT_YOUR_BOT_TOKEN_HERE"
      AUTHORIZED_CHAT_ID: "123456789"
      SHRED_PASSWORD: "your_secret_password"
      WINDOWS_USER: "admin"
      WINDOWS_HOST: "192.168.1.10"
      SHRED_COMMAND: 'powershell -File "C:\\shred_script.ps1"'
    restart: unless-stopped

  api-server:
    build: ./docker/api
    environment:
      API_KEY: "your_secret_key"
      WINDOWS_USER: "admin"
      WINDOWS_HOST: "192.168.1.10"
      SHRED_COMMAND: 'powershell -File "C:\\shred_script.ps1"'
    ports:
      - "8080:8080"
    restart: unless-stopped
